[package]
name = "common"
description = "common utilities for lumen"
version = "0.1.0"
authors = ["Naim A. <naim@abda.nl>"]
edition = "2018"
publish = false

[dependencies]
tokio = {version = "^0.3.1", features = ["full"]}
log = {version = "0.4", features = ["release_max_level_debug"]}
serde = {version = "1.0", features = ["derive"]}
tokio-postgres = {version = "0.6"}
postgres-native-tls = "0.4.0"
native-tls = {version = "0.2"}
futures-util = "0.3"
chrono = {version = "0.4", features = ["serde"]}
toml = "0.5"
